Georgea/tokenize batch
NVIDIA/NeMo-Aligner pull request #352
Opened 2024-10-22 01:09 UTC by gwarmstrong

# What does this PR do ?

Fixes a bug in `tokenize_batch` that occurs when there are more tokens than the specified max sequence length.

# Changelog 
- Please update the [CHANGELOG.md](/CHANGELOG.md) under next version with high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation? Make sure to also update the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/index.html) which contains the tutorials

# Checklist when contributing a new algorithm
- [ ] Does the trainer resume and restore model state all states?
- [ ] Does the trainer support all parallelism techniques(PP, TP, DP)?
- [ ] Does the trainer support `max_steps=-1` and `validation`?
- [ ] Does the trainer only call APIs defined in [alignable_interface.py](/nemo_aligner/models/alignable_interface.py)?
- [ ] Does the trainer have proper logging?

# Additional Information
* Related to # (issue)

2024-10-22 16:31 UTC, terrykong requested changes
Great catch! I've left my comments below

2024-10-22 16:31 UTC, terrykong commented on tests/test_utils.py
> +class _MockTokenizer:
No need to protect this class

2024-10-22 16:31 UTC, terrykong commented on tests/test_utils.py
I think there are a lot of utils so it would probably help to keep them separated. Could you add your changes to a new `test_text_generation_utils.py`?

2024-10-22 16:31 UTC, terrykong commented on tests/test_utils.py
> +    ), f"expected context_tokens_tensor shape to be (2, 30) but got {context_tokens_tensor.shape}"
comment doesn't seem to match assertion

2024-10-22 18:05 UTC, gwarmstrong commented on tests/test_utils.py
> +    ), f"expected context_tokens_tensor shape to be (2, 30) but got {context_tokens_tensor.shape}"
fixed

2024-10-22 18:05 UTC, gwarmstrong commented on tests/test_utils.py
added

2024-10-22 18:05 UTC, gwarmstrong commented on tests/test_utils.py
> +class _MockTokenizer:
made it public

2024-10-22 20:49 UTC, terrykong commented
Needs #354

2024-10-25 20:54 UTC, terrykong approved these changes

2024-10-25 20:54 UTC, merged