feat: DPO support for mcore optimizer and MoE
NVIDIA/NeMo-Aligner pull request #380
Opened 2024-11-05 20:48 UTC by terrykong

# What does this PR do ?
- Finishes up support for mcore optimizer
- adds pad_to_multiple_of for DPO which is a requirement for sequence parallel (which is required for moe models w/ TP)
- adds some tests

# Changelog 
- Please update the [CHANGELOG.md](/CHANGELOG.md) under next version with high level changes in this PR.

# Usage
* You can potentially add a usage example below

```python
# Add a code snippet demonstrating how to use this 
```

# Before your PR is "Ready for review"
**Pre checks**:
- [ ] Make sure you read and followed [Contributor guidelines](/CONTRIBUTING.md)
- [ ] Did you write any new necessary tests?
- [ ] Did you add or update any necessary documentation? Make sure to also update the [NeMo Framework User Guide](https://docs.nvidia.com/nemo-framework/user-guide/latest/index.html) which contains the tutorials

# Checklist when contributing a new algorithm
- [ ] Does the trainer resume and restore model state all states?
- [ ] Does the trainer support all parallelism techniques(PP, TP, DP)?
- [ ] Does the trainer support `max_steps=-1` and `validation`?
- [ ] Does the trainer only call APIs defined in [alignable_interface.py](/nemo_aligner/models/alignable_interface.py)?
- [ ] Does the trainer have proper logging?

# Additional Information
* Related to # (issue)

2024-11-07 17:32 UTC, terrykong commented
The DPO dataset changes should stand on their own, but are needed to test the mcore opt changes for moe. If moe issues take too long to resolve, I'll break this up.

2024-11-22 18:03 UTC, ashors1 approved these changes

2025-01-10 18:37 UTC, gshennvm commented on nemo_aligner/utils/train_utils.py
> +        if not ptl_model.use_mcore_dist_optim:
how do you feel about dropping support for non mcore dist optim? are they equivalent to apex now?

2025-01-10 18:38 UTC, gshennvm commented on nemo_aligner/utils/train_utils.py
> +    ptl_model.megatron_timer_stop("gradient_allreduce")
where is the start here?(maybe i just missed it?)

2025-01-10 18:43 UTC, terrykong commented on nemo_aligner/utils/train_utils.py
> +        if not ptl_model.use_mcore_dist_optim:
yea, i want to do that in a follow up PR (would help our build times immensely). This just adds the feature without breaking apex

2025-01-10 18:44 UTC, terrykong commented on nemo_aligner/utils/train_utils.py
> +    ptl_model.megatron_timer_stop("gradient_allreduce")
https://github.com/NVIDIA/NeMo-Aligner/pull/380/files/4f60e8729a1f7b3683ab92bfa4b1f735aa16f150#diff-2fe1ae18d9ee9628d1cc64471a6124b6bb7c8c8cd9e2a76829d125393a83fd0aR115

2025-01-10 18:46 UTC, gshennvm commented on nemo_aligner/algorithms/supervised.py
> +        self.optimizer.step(closure=None)
do we have to specify the closure now? i thought this was optional?

2025-01-10 20:33 UTC, terrykong commented on nemo_aligner/algorithms/supervised.py
> +        self.optimizer.step(closure=None)
for mcore dist opt it's required, so i just set it everywhere

2025-01-17 22:56 UTC, gshennvm requested changes

2025-01-17 22:56 UTC, gshennvm commented on examples/nlp/gpt/conf/training_rm.yaml
> +  gradient_clip_val: 0.0  # No need to change. Megatron Core optimizer uses this value
is mcore picking up this value properly? if that's the case we should default it to the previous 1.0 to avoid any surprises with the switch

2025-01-17 22:56 UTC, gshennvm commented on examples/nlp/gpt/conf/training_rm.yaml
> +  gradient_clip_val: 0.0  # No need to change. Megatron Core optimizer uses this value
if the above is the case, maybe it's better to pin the value as `${trainer.rm.gradient_clip_val}`

2025-01-17 23:19 UTC, ashors1 commented on examples/nlp/gpt/conf/training_rm.yaml
> +  gradient_clip_val: 0.0  # No need to change. Megatron Core optimizer uses this value
If we set the default to 1.0, I believe we end up doing gradient clipping twice (once in mcore, once in aligner). @terrykong please correct me if I'm wrong here

2025-01-17 23:20 UTC, ashors1 commented on examples/nlp/gpt/conf/training_rm.yaml
> +  gradient_clip_val: 0.0  # No need to change. Megatron Core optimizer uses this value
Oop never mind, the later bits of the code indicate that we expect clipping to be done from mcore

2025-01-17 23:24 UTC, ashors1 commented on nemo_aligner/utils/train_utils.py
>  def grad_reductions(ptl_model):
Is there a reason we can't leverage mcore's [finalize_model_grads](https://github.com/NVIDIA/Megatron-LM/blob/c7bf403ba37ce7ca739a025accac232c75a38966/megatron/core/distributed/finalize_model_grads.py#L212) function directly?

2025-01-21 06:43 UTC, terrykong commented on nemo_aligner/utils/train_utils.py
>  def grad_reductions(ptl_model):
I think we could try to use that instead, but I'd like to defer any cleanup to our refactoring effort. My goal in this PR is to at least reach parity to nemo 1.0 so that we can remove apex ahead of the refactoring effort. WDYT?

2025-01-21 06:49 UTC, terrykong commented on examples/nlp/gpt/conf/training_rm.yaml
> +  gradient_clip_val: 0.0  # No need to change. Megatron Core optimizer uses this value
> if the above is the case, maybe it's better to pin the value as ${trainer.rm.gradient_clip_val} 

Good point. It is probably more jarring to switch over and not get gradient clipping (if it was 0.0). I applied that suggestion in https://github.com/NVIDIA/NeMo-Aligner/pull/380/commits/149f4aaad160d9f4fe5be8589a5200e3cc48b690

2025-01-23 00:12 UTC, ashors1 commented on nemo_aligner/utils/train_utils.py
>  def grad_reductions(ptl_model):
That makes sense to me, thanks!

2025-01-23 00:12 UTC, ashors1 approved these changes

2025-01-23 19:06 UTC, gshennvm approved these changes

2025-01-28 01:37 UTC, merged